/*global it, describe*/
'use strict';


var assert  = require('assert');
var fs      = require('fs');
var path    = require('path');
var svg2ttf = require('../');
var opentype = require('opentype.js');

// Use opentype paser font
function parseFont(src, options) {
  var buffer = new Uint8Array(svg2ttf(src, options).buffer).buffer;

  return opentype.parse(buffer);
}

describe('svg2ttf', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/test.svg'), 'utf-8');
  // var dst = new Uint8Array(fs.readFileSync(path.join(__dirname, 'fixtures/test.ttf')));

  // it('bin compare', function () {
  //   assert.deepStrictEqual(new Uint8Array(svg2ttf(src, { ts: 1457357570703 }).buffer), dst);
  // });

  describe('version', function () {

    it('should throw on bad version value', function () {
      assert.throws(function () {
        svg2ttf(src, { version: 123 });
      });
      assert.throws(function () {
        svg2ttf(src, { version: 'abc' });
      });

      assert.throws(function () {
        svg2ttf(src, { version: '1.  000' });
      });
    });

    it('should set proper version', function () {
      var options;

      // Default version
      assert.strictEqual(parseFont(src).tables.name.version.en, 'Version 1.0');

      options = { ts: 1457357570703, version: '1.0' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.0');

      options = { ts: 1457357570703, version: 'Version 1.0' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.0');

      options = { ts: 1457357570703, version: 'version 1.0' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.0');

      options = { ts: 1457357570703, version: 'version 2.0' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 2.0');
    });

    it('should remove the whitespace in the middle of version', function () {
      var options = { ts: 1457357570703, version: 'version   2.31' };

      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 2.31');

      options = { ts: 1457357570703, version: 'Version \n\t  1.102' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.102');

      options = { ts: 1457357570703, version: 'Version \n\t  1.102  ' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.102');
    });

    it('should remove the whitespace before and after version', function () {
      var options = { ts: 1457357570703, version: '\tversion 2.08   ' };

      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 2.08');

      options = { ts: 1457357570703, version: 'Version 1.90  \n' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 1.90');

      options = { ts: 1457357570703, version: ' 3.0 \n\t' };
      assert.strictEqual(parseFont(src, options).tables.name.version.en, 'Version 3.0');
    });
  });

  describe('copyright', function () {
    it('should remove the whitespace before and after copyright', function () {
      var options;

      // Default copyright
      assert.strictEqual(parseFont(src).tables.name.copyright.en, 'Copyright (C) 2016 by original authors @ fontello.com');

      options = { ts: 1457357570703, copyright: 'foo bar  ' };
      assert.strictEqual(parseFont(src, options).tables.name.copyright.en, 'foo bar');

      options = { ts: 1457357570703, copyright: '   foo bar   ' };
      assert.strictEqual(parseFont(src, options).tables.name.copyright.en, 'foo bar');

      options = { ts: 1457357570703, copyright: '\tFoo bar\n' };
      assert.strictEqual(parseFont(src, options).tables.name.copyright.en, 'Foo bar');

      options = { ts: 1457357570703, copyright: '  Copyright (C) 2016 by original authors @ fontello.com\n' };
      assert.strictEqual(parseFont(src, options).tables.name.copyright.en, 'Copyright (C) 2016 by original authors @ fontello.com');
    });
  });

  describe('description', function () {
    it('should set proper description', function () {
      var options;

      // Default description
      assert.strictEqual(parseFont(src).tables.name.description.en, 'Generated by svg2ttf from Fontello project.');

      options = { description: 'Generated by foo' };
      assert.strictEqual(parseFont(src, options).tables.name.description.en, 'Generated by foo');

      options = { description: ' \tGenerated by foo   ' };
      assert.strictEqual(parseFont(src, options).tables.name.description.en, 'Generated by foo');
    });
  });

  describe('url', function () {
    it('should set proper url', function () {
      var options;

      // Default url
      assert.strictEqual(parseFont(src).tables.name.manufacturerURL.en, 'http://fontello.com');

      options = { url: 'https://foo.com/' };
      assert.strictEqual(parseFont(src, options).tables.name.manufacturerURL.en, 'https://foo.com/');

      options = { url: 'foo bar' };
      assert.strictEqual(parseFont(src, options).tables.name.manufacturerURL.en, 'foo bar');

      options = { url: '\n https://foo.com/   ' };
      assert.strictEqual(parseFont(src, options).tables.name.manufacturerURL.en, 'https://foo.com/');
    });
  });

  describe('familyname', function () {
    it('should set proper familyname', function () {
      var options;

      // Default familyname
      assert.strictEqual(parseFont(src).tables.name.fontFamily.en, 'fontello');

      options = { familyname: 'An icon font' };
      assert.strictEqual(parseFont(src, options).tables.name.fontFamily.en, 'An icon font');

      options = { familyname: '  An icon font \n' };
      assert.strictEqual(parseFont(src, options).tables.name.fontFamily.en, 'An icon font');
    });
  });

  describe('subfamilyname', function () {
    it('should set proper subfamilyname', function () {
      var options;

      // Default subfamilyname
      assert.strictEqual(parseFont(src).tables.name.fontSubfamily.en, 'Regular');

      options = { subfamilyname: 'An icon font Regular' };
      assert.strictEqual(parseFont(src, options).tables.name.fontSubfamily.en, 'An icon font Regular');

      options = { subfamilyname: '  An icon font Regular \t\n' };
      assert.strictEqual(parseFont(src, options).tables.name.fontSubfamily.en, 'An icon font Regular');
    });
  });

  describe('fullname', function () {
    it('should set proper fullname', function () {
      var options;

      // Default fullname
      assert.strictEqual(parseFont(src).tables.name.fullName.en, 'fontello');

      options = { fullname: 'An icon font' };
      assert.strictEqual(parseFont(src, options).tables.name.fullName.en, 'An icon font');

      options = { fullname: ' \nAn icon font  ' };
      assert.strictEqual(parseFont(src, options).tables.name.fullName.en, 'An icon font');
    });
  });


  // https://docs.microsoft.com/en-us/typography/opentype/spec/os2#achvendid
  describe('lineGap and achVendID', function () {
    it('achVendID', function () {
      // TODO：Should be changed to NONE
      // https://github.com/googlefonts/fontbakery/blob/6d184b324beda409f4d670ab957d1c079d0bd814/Lib/fontbakery/profiles/googlefonts.py#L869-L878
      assert.strictEqual(parseFont(src).tables.os2.achVendID, 'PfEd');
    });

    it('os2.sTypoLineGap', function () {
      assert.strictEqual(parseFont(src).tables.os2.sTypoLineGap, 90);
    });

    it('hhea.lineGap', function () {
      assert.strictEqual(parseFont(src).tables.hhea.lineGap, 0);
    });

    // it('sTypoLineGap == lineGap', function () {
    //   assert.strictEqual(parseFont(src).tables.hhea.lineGap, parseFont(src).tables.os2.sTypoLineGap);
    // });
  });

});

describe('test arrow.svg', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/arrow.svg'), 'utf-8');
  var tables = parseFont(src).tables;

  fs.writeFileSync(path.join(__dirname, 'fixtures/arrow.ttf'), svg2ttf(src).buffer);

  it('os2.usWinAscent', function () {
    // 32148 is wrong
    assert.strictEqual(tables.os2.usWinAscent, 988);
  });

  it('head.yMax', function () {
    // 32148 is wrong
    assert.strictEqual(tables.head.yMax, 896);
  });

  it('os2.usWinDescent', function () {
    assert.strictEqual(tables.os2.usWinDescent, 128);
  });

  it('head.yMin', function () {
    assert.strictEqual(tables.head.yMin, -130);
  });
});

describe('test shenhetongguo.svg', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/shenhetongguo.svg'), 'utf-8');
  var tables = parseFont(src).tables;

  it('head.yMin', function () {
    assert.strictEqual(tables.head.yMin, -78);
  });

  it('head.xMax', function () {
    assert.strictEqual(tables.head.xMax, 2728);
  });
});

describe('test shenheweitongguo.svg', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/shenheweitongguo.svg'), 'utf-8');
  var tables = parseFont(src).tables;

  fs.writeFileSync(path.join(__dirname, 'fixtures/shenheweitongguo.ttf'), svg2ttf(src).buffer);

  it('head.yMin', function () {
    // 27274 is wrong
    assert.strictEqual(tables.head.yMin, 0);
  });
  it('head.xMax', function () {
    // -13440 is wrong
    assert.strictEqual(tables.head.xMax, 2258);
  });
});

describe('test wuxushenhe.svg', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/wuxushenhe.svg'), 'utf-8');
  var tables = parseFont(src).tables;

  it('head.yMin', function () {
    assert.strictEqual(tables.head.yMin, 0);
  });

  it('head.xMax', function () {
    assert.strictEqual(tables.head.xMax, 2045);
  });
});

describe('test yezi.svg', function () {
  var src = fs.readFileSync(path.join(__dirname, 'fixtures/yezi.svg'), 'utf-8');
  var tables = parseFont(src).tables;

  // Use font data generated by nanoemoji for comparison.
  it('head.xMin', function () {
    // 9235 is wrong
    assert.strictEqual(tables.head.xMin, 481);
  });

  it('head.yMin', function () {
    // -11936 is wrong
    assert.strictEqual(tables.head.yMin, 458);
  });

  it('head.xMax', function () {
    // 30060 is wrong
    assert.strictEqual(tables.head.xMax, 993);
  });

  it('head.yMax', function () {
    // -9161 is wrong
    assert.strictEqual(tables.head.yMax, 745);
  });
});
